"""add password column to db

Revision ID: 879ddee78c3f
Revises: 8f5e53ea4fbe
Create Date: 2024-12-17 11:51:55.573597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879ddee78c3f'
down_revision = '8f5e53ea4fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_projects')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('brand_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('_password_hash')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('brand_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.create_table('_alembic_tmp_projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('logo', sa.VARCHAR(), nullable=True),
    sa.Column('brand_name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
